name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/go-versions@v1
        with:
          go-version: '1.22'

      - name: Build Go binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o video-server main.go

      - name: Create Release Package
        run: |
          zip -r go-video-streamer-linux.zip video-server run.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: go-video-streamer-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
